# Check Lua Formatting
name: Check Lua Formatting
on: pull_request

jobs:
  stylua-check:
    name: Stylua Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Stylua Check
        uses: JohnnyMorganz/stylua-action@v3
        with:
          version: latest
          args: --check .

